name: cine
recipe: drupal9
config:
  webroot: web
proxy:
  pma:
    - pma.cine.lndo.site
services:
  db:
    type: mysql:8.0.32
    portforward: true
    creds:
      database: dbcine
      user: dbuser
      password: dbpass
  pma:
    type: phpmyadmin
    hosts:
      - db